/**
 * Strategic Planner - Uses AI to analyze preferences and POI distribution,
 * generating optimization strategies for the waypoint optimizer.
 */


import type { LLMProvider } from '../providers/llm/interface';
import type {
  ParsedPreferences,
  RankedPOI,
  SearchSpace,
  POIType,
  LatLng,
} from '@mappy/shared';

/**
 * Optimization strategy generated by AI strategic planning.
 */
export interface OptimizationStrategy {
  /** POI types to prioritize (weighted) */
  poiPriorities: Record<POIType, number>;

  /** Geographic regions to focus on (cluster IDs from spatial analysis) */
  priorityRegions: string[];

  /** Optimization style: concentrated (tight loops) vs dispersed (explore farther) */
  optimizationStyle: 'concentrated' | 'dispersed' | 'balanced';

  /** Risk tolerance for going farther for better POIs (0-1) */
  riskTolerance: number;

  /** Diversity importance (0-1): balance between best POIs vs variety */
  diversityWeight: number;

  /** AI reasoning explanation */
  reasoning: string;
}

/**
 * Geographic cluster of POIs for spatial analysis.
 */
interface POICluster {
  id: string;
  center: LatLng;
  pois: RankedPOI[];
  avgScore: number;
  dominantTypes: POIType[];
}

export class StrategicPlanner {
  constructor(private llm: LLMProvider) { }

  /**
   * Generate optimization strategy via AI strategic reasoning.
   */
  async generateStrategy(
    preferences: ParsedPreferences,
    pois: RankedPOI[],
    searchSpace: SearchSpace,
    origin: LatLng
  ): Promise<OptimizationStrategy> {
    // Spatial analysis: cluster POIs geographically
    const clusters = this.clusterPOIs(pois, searchSpace);

    // Summarize POI distribution for AI
    const poiSummary = this.summarizePOIs(pois, clusters);

    // Build compact prompt for AI strategic planning
    const prompt = this.buildStrategyPrompt(preferences, poiSummary, origin);

    try {
      const result = await this.llm.generateJSON<{
        poi_priorities: Record<string, number>;
        optimization_style: 'concentrated' | 'dispersed' | 'balanced';
        risk_tolerance: number;
        diversity_weight: number;
        priority_regions?: string[];
        reasoning: string;
      }>(prompt, {
        type: 'object',
        properties: {
          poi_priorities: {
            type: 'object',
            // Define that this is a dynamic object with number values
            additionalProperties: { type: 'number' }
          },
          optimization_style: {
            type: 'string',
            enum: ['concentrated', 'dispersed', 'balanced']
          },
          risk_tolerance: {
            type: 'number',
            minimum: 0,
            maximum: 1
          },
          diversity_weight: {
            type: 'number',
            minimum: 0,
            maximum: 1
          },
          reasoning: {
            type: 'string',
            maxLength: 200
          },
        },
        required: ['poi_priorities', 'optimization_style', 'risk_tolerance', 'diversity_weight', 'reasoning'],
      }, {
        systemInstruction: 'Strategic route planner. Return JSON only.',
        temperature: 0.2,
        maxTokens: 1024,
      });

      // Filter out _dynamic and other invalid POI types
      const filteredPriorities: Record<string, number> = {};
      for (const [key, value] of Object.entries(result.poi_priorities)) {
        if (key !== '_dynamic' && typeof value === 'number') {
          filteredPriorities[key] = value;
        }
      }

      return {
        poiPriorities: filteredPriorities as Record<POIType, number>,
        priorityRegions: [],  // Removed from prompt to keep it ultra-compact
        optimizationStyle: result.optimization_style,
        riskTolerance: result.risk_tolerance,
        diversityWeight: result.diversity_weight,
        reasoning: result.reasoning || 'Strategic optimization based on preferences',
      };
    } catch (error) {
      console.warn('[StrategicPlanner] AI strategy generation failed, using heuristic fallback:', error);
      return this.generateHeuristicStrategy(preferences, pois);
    }
  }

  /**
   * Cluster POIs geographically for spatial analysis.
   * Uses simple grid-based clustering based on searchSpace grid.
   */
  private clusterPOIs(pois: RankedPOI[], searchSpace: SearchSpace): POICluster[] {
    const clusters = new Map<string, POICluster>();

    for (const poi of pois) {
      // Find nearest grid cell
      const cell = searchSpace.grid.cells.find(c =>
        poi.location.lat >= c.bounds.south &&
        poi.location.lat <= c.bounds.north &&
        poi.location.lng >= c.bounds.west &&
        poi.location.lng <= c.bounds.east
      );

      const cellId = cell?.id || 'default';

      if (!clusters.has(cellId)) {
        clusters.set(cellId, {
          id: cellId,
          center: cell?.center || poi.location,
          pois: [],
          avgScore: 0,
          dominantTypes: [],
        });
      }

      clusters.get(cellId)!.pois.push(poi);
    }

    // Calculate cluster metrics
    for (const cluster of clusters.values()) {
      cluster.avgScore = cluster.pois.reduce((sum, p) => sum + p.score.composite, 0) / cluster.pois.length;

      // Find dominant types
      const typeCounts = new Map<POIType, number>();
      for (const poi of cluster.pois) {
        typeCounts.set(poi.type, (typeCounts.get(poi.type) || 0) + 1);
      }
      cluster.dominantTypes = Array.from(typeCounts.entries())
        .sort((a, b) => b[1] - a[1])
        .slice(0, 2)
        .map(([type]) => type);
    }

    return Array.from(clusters.values()).sort((a, b) => b.avgScore - a.avgScore);
  }

  /**
   * Summarize POI distribution for ULTRA-COMPACT prompt.
   * Shows ALL POI types so AI knows what's available.
   */
  private summarizePOIs(pois: RankedPOI[], _clusters: POICluster[]): string {
    const typeDistribution = new Map<POIType, number>();
    for (const poi of pois) {
      typeDistribution.set(poi.type, (typeDistribution.get(poi.type) || 0) + 1);
    }

    // Show ALL POI types so AI knows what's available (still compact format)
    const typeSummary = Array.from(typeDistribution.entries())
      .sort((a, b) => b[1] - a[1])
      .map(([type, count]) => `${type}:${count}`)
      .join(',');

    return `${pois.length} POIs: ${typeSummary}`;
  }

  /**
   * Build strategic planning prompt for AI (Optimized for JSON response).
   */
  private buildStrategyPrompt(
    preferences: ParsedPreferences,
    poiSummary: string,
    _origin: LatLng
  ): string {
    const prefSummary = this.summarizePreferences(preferences);

    // Direct, structured prompt that aligns with JSON schema
    return `Analyze and create optimization strategy.

USER: ${prefSummary}
AVAILABLE: ${poiSummary}

Return JSON with:
{
  "poi_priorities": { "type1": weight, "type2": weight, ... },
  "optimization_style": "concentrated" | "dispersed" | "balanced",
  "risk_tolerance": 0.0-1.0,
  "diversity_weight": 0.0-1.0,
  "reasoning": "brief explanation"
}`;
  }

  /**
   * Summarize parsed preferences with enough detail for AI reasoning.
   */
  private summarizePreferences(preferences: ParsedPreferences): string {
    const parts: string[] = [];

    // Hard constraints (distance)
    for (const c of preferences.constraints.hard) {
      if (c.type === 'distance') {
        parts.push(`${c.value}${c.unit} route`);
      }
    }

    // Soft constraints (scenic, POI types)
    const interests: string[] = [];
    for (const c of preferences.constraints.soft) {
      if (c.type === 'scenic') {
        interests.push('scenic views');
      } else if (c.type === 'poi' && c.preferences) {
        const types = Object.keys(c.preferences as object)
          .filter(k => k !== '_dynamic');
        interests.push(...types);
      }
    }

    if (interests.length > 0) {
      parts.push(`interested in ${interests.join(', ')}`);
    }

    return parts.length > 0 ? parts.join(', ') : 'general exploration route';
  }

  /**
   * Heuristic fallback strategy when LLM is unavailable.
   */
  private generateHeuristicStrategy(
    preferences: ParsedPreferences,
    pois: RankedPOI[]
  ): OptimizationStrategy {
    const poiPriorities: Record<string, number> = {};

    // Analyze POI distribution to understand what's available
    const poiTypeCounts = new Map<POIType, number>();
    for (const poi of pois) {
      poiTypeCounts.set(poi.type, (poiTypeCounts.get(poi.type) || 0) + 1);
    }

    // Extract user preferences
    let isScenicFocused = false;
    const userRequestedTypes = new Set<string>();

    for (const c of preferences.constraints.soft) {
      if (c.type === 'scenic') {
        isScenicFocused = true;
        // Prioritize scenic POI types
        poiPriorities['viewpoint'] = 2.0;
        poiPriorities['park'] = 1.8;
        poiPriorities['water'] = 1.8;
        poiPriorities['nature'] = 1.7;
        poiPriorities['scenic'] = 1.9;
      } else if (c.type === 'poi' && c.preferences) {
        // Extract user-requested POI types
        for (const [key, val] of Object.entries(c.preferences as Record<string, number>)) {
          if (key !== '_dynamic' && typeof val === 'number') {
            userRequestedTypes.add(key);
            poiPriorities[key] = Math.min(val * 1.5, 2.0); // Cap at 2.0
          }
        }
      }
    }

    // Intelligent defaults: prioritize what's abundant and relevant
    if (Object.keys(poiPriorities).length === 0) {
      // No specific preferences, use data-driven defaults
      const topTypes = Array.from(poiTypeCounts.entries())
        .sort((a, b) => b[1] - a[1])
        .slice(0, 5);

      for (const [type, count] of topTypes) {
        // Weight by abundance (more POIs = better coverage)
        poiPriorities[type] = 1.0 + (count / pois.length) * 0.8;
      }
    }

    // Determine optimization style based on preferences and data
    let optimizationStyle: 'concentrated' | 'dispersed' | 'balanced';
    let riskTolerance: number;
    let diversityWeight: number;

    if (isScenicFocused) {
      // Scenic routes: explore farther for views
      optimizationStyle = 'dispersed';
      riskTolerance = 0.7;
      diversityWeight = 0.7; // High variety of scenic spots
    } else if (userRequestedTypes.size > 3) {
      // Many interests: balanced exploration
      optimizationStyle = 'balanced';
      riskTolerance = 0.6;
      diversityWeight = 0.8; // High variety
    } else if (userRequestedTypes.size > 0) {
      // Specific interests: concentrated visits
      optimizationStyle = 'concentrated';
      riskTolerance = 0.4; // Stick to requested types nearby
      diversityWeight = 0.5;
    } else {
      // General exploration: balanced
      optimizationStyle = 'balanced';
      riskTolerance = 0.5;
      diversityWeight = 0.6;
    }

    const reasoning = `Heuristic strategy: ${isScenicFocused ? 'scenic exploration' : userRequestedTypes.size > 0 ? `focused on ${Array.from(userRequestedTypes).join(', ')}` : 'general exploration'} with ${poiTypeCounts.size} POI types available`;

    return {
      poiPriorities: poiPriorities as Record<POIType, number>,
      priorityRegions: [],
      optimizationStyle,
      riskTolerance,
      diversityWeight,
      reasoning,
    };
  }
}
